server:
  port: 2042

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  application:
    name: deal

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: false
        hypersistence.utils.enable_types_contributor: false
    show-sql: true

  sql:
    init:
      mode: always

  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:deal-db;MODE=PostgreSQL;INIT=CREATE DOMAIN IF NOT EXISTS JSONB AS JSON;
    username: test
    password: test
  h2:
    console:
      enabled: true

  cloud:
    feign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        transaction: INFO
        transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG

rest:
  calculator:
    host: http://localhost:2041/calculator

app:
  kafka:
    enabled: true

kafka:
  bootstrapAddress: localhost:9091
  groupId: group1