spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  code: "123"
  kafka:
    enabled: true

kafka:
  bootstrapAddress: localhost:9091
  groupId: group1

server:
  port: 2044

gateway:
  host: http://localhost:2045
  path: /deal/document/
