name: ms-calculator-ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -f calculator/pom.xml clean install

      - name: Run tests with Maven
        run: mvn -f calculator/pom.xml test

      - name: Code coverage with JaCoCo
        run: mvn -f calculator/pom.xml jacoco:report

      - name: Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          file: './calculator/target/site/jacoco/jacoco.xml'
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -f calculator/pom.xml verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=geo-tat_credit-bank
