name: ms-dossier-ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -f dossier/pom.xml clean install

      - name: Run tests with Maven
        run: mvn -f dossier/pom.xml test

      - name: Code coverage with JaCoCo
        run: mvn -f dossier/pom.xml jacoco:report

      - name: Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          file: './dossier/target/site/jacoco/jacoco.xml'
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        with:
          token: ${{ secrets.SONAR_TOKEN }}
